version: '3.7'
services:
  app:
    build:
      context: .
    stdin_open: true
    tty: true
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - bundle_data:/usr/local/bundle
    environment:
      EDITOR: vim
volumes:
  bundle_data:
    driver: local
